export interface Product {
  id: number;
  cat: string;
  name: string;
  qty: string;
  price: string;
}

export const PRODUCTS: Product[] = [
  // ── MIELL ──────────────────────────────────────────────────
  {id:0,   cat:"MIELL",    name:"Miell Diamond Tip00 Universal",                              qty:"1 kg",               price:"115"},
  {id:1,   cat:"MIELL",    name:"Miell Diamond Triplo",                                       qty:"1kg",                price:"115"},
  {id:2,   cat:"MIELL",    name:"Mariani miell per Pizza - Tip00 | Origjina : Itali",         qty:"25 kg",              price:"3200"},
  {id:3,   cat:"MIELL",    name:"Mariani miell Volare Forteper Pizza | Origjina : Itali",     qty:"12.5 kg",            price:"3300"},
  {id:4,   cat:"MIELL",    name:"Divella Farina 00",                                          qty:"1 kg",               price:"80"},
  {id:5,   cat:"MIELL",    name:"Pizza Top 00 | origjina : Greqi",                            qty:"25 kg",              price:"2625"},
  {id:6,   cat:"MIELL",    name:"Soft Miell 00 | origjina : Greqi",                           qty:"25 kg",              price:"2750"},
  {id:7,   cat:"MIELL",    name:"Irca Miell i gatshem per Krepa",                             qty:"10 kg",              price:"7800"},
  // ── PERBERES EMBELSIRASH ───────────────────────────────────
  {id:8,   cat:"EMBELSIRA",name:"Irca çokokrem nocciolata 12% | Origjina : Itali",           qty:"13 kg",              price:"7150"},
  {id:9,   cat:"EMBELSIRA",name:"VELA ( Pistachio ) 15% | Origjina : Itali",                 qty:"6 kg",               price:"6150"},
  {id:10,  cat:"EMBELSIRA",name:"Nutkao ( Pistachio ) 10% | origjina : Itali",               qty:"6 kg",               price:"6200"},
  {id:11,  cat:"EMBELSIRA",name:"Nutkao 7% Lajthi | origjina : Itali",                       qty:"6 kg",               price:"3480"},
  {id:12,  cat:"EMBELSIRA",name:"Irca Nocciolata - Çokokrem Lajthi 12%",                     qty:"13 kg",              price:"6500"},
  {id:13,  cat:"EMBELSIRA",name:"Irca Çokokrem i bardhe",                                    qty:"13 kg",              price:"6500"},
  {id:14,  cat:"EMBELSIRA",name:"Hulala Pana per embelsira",                                 qty:"1L",                 price:"280"},
  {id:15,  cat:"EMBELSIRA",name:"CokoMagic - çokokrem per mbushje",                          qty:"12 kg",              price:"4200"},
  {id:16,  cat:"EMBELSIRA",name:"Sheqer Pluhur - Teuta",                                     qty:"500 gr",             price:"75"},
  {id:17,  cat:"EMBELSIRA",name:"Migro Zucchero Di Canna",                                   qty:"1 kg",               price:"170"},
  {id:18,  cat:"EMBELSIRA",name:"Mjale Morava",                                              qty:"200 cop x 18 gr",    price:"4320"},
  {id:19,  cat:"EMBELSIRA",name:"Mjalte Morava",                                             qty:"288 cop x 12 gr",    price:"3600"},
  {id:20,  cat:"EMBELSIRA",name:"Reçel Luleshtrydhe Morava",                                 qty:"200 cop x 20 gr",    price:"3000"},
  {id:21,  cat:"EMBELSIRA",name:"Reçel Pjeshke Morava",                                      qty:"200 cop x 20 gr",    price:"3000"},
  {id:22,  cat:"EMBELSIRA",name:"Reçel Qershie Morava",                                      qty:"200 cop x 20 gr",    price:"3000"},
  // ── TE KONSERVUARA ─────────────────────────────────────────
  {id:23,  cat:"KONSERVA", name:"SACLA - Carciofi Fettine Olio | Org : Itali",               qty:"3 kg",               price:"950"},
  {id:24,  cat:"KONSERVA", name:"SACLA - Ullinj jeshil te prere rondele | Org : Itali",      qty:"2 kg",               price:"1400"},
  {id:25,  cat:"KONSERVA", name:"SACLA - ullinj te zi Rondelle ( te prere )",                qty:"5 kg",               price:"1400"},
  {id:26,  cat:"KONSERVA", name:"SACLA - ullinj te zijn pa berthame",                        qty:"5 kg",               price:"1400"},
  {id:27,  cat:"KONSERVA", name:"SACLA - Kerpudha Champignon Al Naturale",                   qty:"3 kg",               price:"750"},
  {id:28,  cat:"KONSERVA", name:"SACLA - Carciofi Al Naturale",                              qty:"3 kg",               price:"750"},
  {id:29,  cat:"KONSERVA", name:"Dillio - Domate te thara ne vaj",                           qty:"3.1 L",              price:"2100"},
  {id:30,  cat:"KONSERVA", name:"Pomodori Secchi",                                           qty:"1 L",                price:"700"},
  {id:31,  cat:"KONSERVA", name:"Ton Peshku - Amati",                                        qty:"1 kg",               price:"1050"},
  {id:32,  cat:"KONSERVA", name:"Konserve Tuna",                                             qty:"1 kg",               price:"720"},
  {id:33,  cat:"KONSERVA", name:"Novi Miser",                                                qty:"2.1 kg",             price:"760"},
  {id:34,  cat:"KONSERVA", name:"Fileto Acuge",                                              qty:"720 gr",             price:"1250"},
  // ── PERBERES GATIMI ────────────────────────────────────────
  {id:35,  cat:"GATIM",    name:"Hole Cooking - Pana Kuzhine",                               qty:"10 cop x 1L",        price:"2300"},
  {id:36,  cat:"GATIM",    name:"Prima Gastro Pana",                                         qty:"1L",                 price:"240"},
  {id:37,  cat:"GATIM",    name:"Teuta Sode Buke",                                           qty:"500 gr",             price:"80"},
  {id:38,  cat:"GATIM",    name:"Proser Vaj Bimor 18L",                                      qty:"18 L",               price:"4200"},
  {id:39,  cat:"GATIM",    name:"Olitalia Vaj Ulliri di Sansa",                              qty:"5 L",                price:"2450"},
  {id:40,  cat:"GATIM",    name:"Desantis Vaj ulliri",                                       qty:"1 L",                price:"750"},
  {id:41,  cat:"GATIM",    name:"Levante Vaj Palm",                                          qty:"25 L",               price:"7500"},
  // ── FRUTA & PERIME ─────────────────────────────────────────
  {id:42,  cat:"FRUTA",    name:"qepe e bardhe",                                             qty:"1 kg",               price:"80"},
  {id:43,  cat:"FRUTA",    name:"brokoli",                                                   qty:"1 kg",               price:"140"},
  {id:44,  cat:"FRUTA",    name:"domate roze vendi",                                         qty:"1 kg",               price:"85"},
  {id:45,  cat:"FRUTA",    name:"domate e kuqe vendi",                                       qty:"1 kg",               price:"85"},
  {id:46,  cat:"FRUTA",    name:"qepe e kuqe",                                               qty:"1 kg",               price:"100"},
  {id:47,  cat:"FRUTA",    name:"patate vendi",                                              qty:"1 kg",               price:"70"},
  {id:48,  cat:"FRUTA",    name:"laker e kuqe",                                              qty:"1 kg",               price:"95"},
  {id:49,  cat:"FRUTA",    name:"panxhar",                                                   qty:"1 kg",               price:"105"},
  {id:50,  cat:"FRUTA",    name:"pomodorini vasket",                                         qty:"1 kg",               price:"290"},
  {id:51,  cat:"FRUTA",    name:"qepe e njome",                                              qty:"1 kg",               price:"220"},
  {id:52,  cat:"FRUTA",    name:"hudher e thate",                                            qty:"1 kg",               price:"230"},
  {id:53,  cat:"FRUTA",    name:"kastravec",                                                 qty:"1 kg",               price:"85"},
  {id:54,  cat:"FRUTA",    name:"spec i kuq chilli",                                         qty:"1 kg",               price:"870"},
  {id:55,  cat:"FRUTA",    name:"spec pikant jeshil",                                        qty:"1 kg",               price:"490"},
  {id:56,  cat:"FRUTA",    name:"Pomodorini",                                                qty:"1 kg",               price:"150"},
  {id:57,  cat:"FRUTA",    name:"Kerpudha vasket",                                           qty:"0.25 kg",            price:"130"},
  {id:58,  cat:"FRUTA",    name:"Rukola Gjethe gjere vendi",                                 qty:"1 kg",               price:"250"},
  {id:59,  cat:"FRUTA",    name:"Rukola Gjethe imet vendi",                                  qty:"1 kg",               price:"250"},
  {id:60,  cat:"FRUTA",    name:"Patate Importi",                                            qty:"1 kg",               price:"65"},
  {id:61,  cat:"FRUTA",    name:"Borzilok",                                                  qty:"100 g",              price:"170"},
  {id:62,  cat:"FRUTA",    name:"Mango",                                                     qty:"1 kg",               price:"450"},
  {id:63,  cat:"FRUTA",    name:"Limon Importi",                                             qty:"1 kg",               price:"250"},
  {id:64,  cat:"FRUTA",    name:"Majdanoz",                                                  qty:"Tufë",               price:"140"},
  {id:65,  cat:"FRUTA",    name:"Bishtaja",                                                  qty:"1 kg",               price:"450"},
  {id:66,  cat:"FRUTA",    name:"Manaferre Vaskete",                                         qty:"125 g",              price:"450"},
  {id:67,  cat:"FRUTA",    name:"PORTOKALL IMPORTI CILESI E PARE",                           qty:"1 kg",               price:"160"},
  {id:68,  cat:"FRUTA",    name:"SPINAQ IMPORTI",                                            qty:"1 kg",               price:"620"},
  {id:69,  cat:"FRUTA",    name:"Patate Triumph 11x11",                                      qty:"2.5 kg",             price:"425"},
  {id:70,  cat:"FRUTA",    name:"Karrota",                                                   qty:"1 kg",               price:"110"},
  {id:71,  cat:"FRUTA",    name:"Kopër",                                                     qty:"Tufë",               price:"150"},
  {id:72,  cat:"FRUTA",    name:"Ananas Dole",                                               qty:"1 kg",               price:"200"},
  {id:73,  cat:"FRUTA",    name:"Molle Jeshile Vendi",                                       qty:"1 kg",               price:"120"},
  {id:74,  cat:"FRUTA",    name:"Mente",                                                     qty:"1 kg",               price:"1700"},
  {id:75,  cat:"FRUTA",    name:"Banane",                                                    qty:"1 kg",               price:"159"},
  {id:76,  cat:"FRUTA",    name:"Kivi",                                                      qty:"1 kg",               price:"220"},
  {id:77,  cat:"FRUTA",    name:"Mandarina",                                                 qty:"1 kg",               price:"200"},
  {id:78,  cat:"FRUTA",    name:"Rrush i Bardhë Importi",                                    qty:"1 kg",               price:"500"},
  {id:79,  cat:"FRUTA",    name:"Rrush i Zi Importi",                                        qty:"1 kg",               price:"500"},
  {id:80,  cat:"FRUTA",    name:"Hudhër e Njomë",                                            qty:"1 kg",               price:"190"},
  {id:81,  cat:"FRUTA",    name:"Luleshtrydhe Vaskete",                                      qty:"500 g",              price:"150"},
  {id:82,  cat:"FRUTA",    name:"Shegë Importi e Athet",                                     qty:"1 kg",               price:"450"},
  {id:83,  cat:"FRUTA",    name:"Finok",                                                     qty:"1 kg",               price:"230"},
  {id:84,  cat:"FRUTA",    name:"Kungull i Zi",                                              qty:"1 kg",               price:"100"},
  {id:85,  cat:"FRUTA",    name:"Patlixhan",                                                 qty:"1 kg",               price:"310"},
  {id:86,  cat:"FRUTA",    name:"Lime",                                                      qty:"1 kg",               price:"330"},
  {id:87,  cat:"FRUTA",    name:"Sallatë Jeshile",                                           qty:"1 kg",               price:"115"},
  {id:88,  cat:"FRUTA",    name:"Pjeshka",                                                   qty:"1 kg",               price:"100"},
  {id:89,  cat:"FRUTA",    name:"Qershi",                                                    qty:"1 kg",               price:"231"},
  {id:90,  cat:"FRUTA",    name:"Spinaq Vendi",                                              qty:"1 kg",               price:"135"},
  {id:91,  cat:"FRUTA",    name:"Pomodorini Rifuxho",                                        qty:"1 kg",               price:"150"},
  {id:92,  cat:"FRUTA",    name:"Shalqi pa fara",                                            qty:"",                   price:"95"},
  {id:93,  cat:"FRUTA",    name:"Patate Steakhouse Agrina Premium",                          qty:"4 x 2.5 kg",         price:"450"},
  {id:94,  cat:"FRUTA",    name:"Patate 11x11",                                              qty:"2.5 kg",             price:"525"},
  {id:95,  cat:"FRUTA",    name:"Molle Fuji Importi",                                        qty:"1 kg",               price:"160"},
  {id:96,  cat:"FRUTA",    name:"Molle Starking Importi",                                    qty:"1 kg",               price:"160"},
  {id:97,  cat:"FRUTA",    name:"Molle Gold Importi",                                        qty:"1 kg",               price:"160"},
  {id:98,  cat:"FRUTA",    name:"Molle Jeshile Importi",                                     qty:"1 kg",               price:"160"},
  {id:99,  cat:"FRUTA",    name:"Molle Starking Vendi",                                      qty:"1 kg",               price:"120"},
  {id:100, cat:"FRUTA",    name:"Spec per Mbushje",                                          qty:"1 kg",               price:"140"},
  {id:101, cat:"FRUTA",    name:"Kungull Jeshil",                                            qty:"1 kg",               price:"80"},
  {id:102, cat:"FRUTA",    name:"Kastravec i Shkurter",                                      qty:"1 kg",               price:"85"},
  {id:103, cat:"FRUTA",    name:"Laker Sallate",                                             qty:"1 kg",               price:"95"},
  {id:104, cat:"FRUTA",    name:"Laker e Bardhe",                                            qty:"1 kg",               price:"65"},
  {id:105, cat:"FRUTA",    name:"Patate Wedges me Lekure",                                   qty:"2.5 kg",             price:"725"},
  {id:106, cat:"FRUTA",    name:"Perime e Perzier",                                          qty:"10 kg",              price:"1750"},
  {id:107, cat:"FRUTA",    name:"Bishtaje e Gjelber",                                        qty:"10 kg",              price:"2000"},
  {id:108, cat:"FRUTA",    name:"Bizele Rifuxho",                                            qty:"10 kg",              price:"1500"},
  {id:109, cat:"FRUTA",    name:"Rrush Francez Vasketa",                                     qty:"",                   price:"490"},
  {id:110, cat:"FRUTA",    name:"Papaya",                                                    qty:"1 kg",               price:"10500"},
  {id:111, cat:"FRUTA",    name:"Patellxhan Importi",                                        qty:"1 kg",               price:"260"},
  {id:112, cat:"FRUTA",    name:"Mjedra Vaskete",                                            qty:"",                   price:"420"},
  {id:113, cat:"FRUTA",    name:"Rambutan",                                                  qty:"1 kg",               price:"2000"},
  {id:114, cat:"FRUTA",    name:"Mandarina Kumkuat",                                         qty:"1 kg",               price:"1200"},
  {id:115, cat:"FRUTA",    name:"Molle Zagorin",                                             qty:"1 kg",               price:"180"},
  {id:116, cat:"FRUTA",    name:"Kungull i Embel",                                           qty:"1 kg",               price:"210"},
  {id:117, cat:"FRUTA",    name:"Patate Egjipti",                                            qty:"1 kg",               price:"75"},
  {id:118, cat:"FRUTA",    name:"Kivi Zespri",                                               qty:"1 kg",               price:"670"},
  {id:119, cat:"FRUTA",    name:"Kerpudha Piopini",                                          qty:"150 g",              price:"200"},
  {id:120, cat:"FRUTA",    name:"Kërpudha Agaricus e Bardhë Vasketë",                        qty:"",                   price:"210"},
  {id:121, cat:"FRUTA",    name:"Kerpudha e Bardhe Rifuxho Arke Plastike",                   qty:"2.5 kg",             price:"950"},
  {id:122, cat:"FRUTA",    name:"Fik i Thatë",                                               qty:"5 kg",               price:"1200"},
  {id:123, cat:"FRUTA",    name:"Lyche",                                                     qty:"1 kg",               price:"2100"},
  {id:124, cat:"FRUTA",    name:"Dardha Conference",                                         qty:"1 kg",               price:"250"},
  {id:125, cat:"FRUTA",    name:"Boronica",                                                  qty:"1 kg",               price:"990"},
  {id:126, cat:"FRUTA",    name:"Artichoke / Argjinare",                                     qty:"1 kg",               price:"570"},
  {id:127, cat:"FRUTA",    name:"Topinambur",                                                qty:"1 kg",               price:"570"},
  {id:128, cat:"FRUTA",    name:"Arrë Kokosi me Pipë",                                       qty:"",                   price:"400"},
  {id:129, cat:"FRUTA",    name:"Arra e Pjekur",                                             qty:"1 kg",               price:"550"},
  {id:130, cat:"FRUTA",    name:"Fik i Thatë",                                               qty:"3 kg",               price:"1150"},
  {id:131, cat:"FRUTA",    name:"Artichoke",                                                 qty:"1 kg",               price:"450"},
  {id:132, cat:"FRUTA",    name:"Spec Padron",                                               qty:"1 kg",               price:"980"},
  {id:133, cat:"FRUTA",    name:"Spec Jalapeno",                                             qty:"1 kg",               price:"880"},
  {id:134, cat:"FRUTA",    name:"Presh Tufë",                                                qty:"1 kg",               price:"60"},
  {id:135, cat:"FRUTA",    name:"Mollë Jeshile me Arkë",                                     qty:"10 kg",              price:"1200"},
  {id:136, cat:"FRUTA",    name:"Mollë Gold Vendi me Arkë",                                  qty:"10 kg",              price:"1200"},
  {id:137, cat:"FRUTA",    name:"Karrotë Qese",                                              qty:"5 kg",               price:"550"},
  {id:138, cat:"FRUTA",    name:"Banane Dole Arkë",                                          qty:"19 kg",              price:"2831"},
  {id:139, cat:"FRUTA",    name:"Radikio",                                                   qty:"1 kg",               price:"120"},
  {id:140, cat:"FRUTA",    name:"Dragon Fruit",                                              qty:"1 kg",               price:"1900"},
  {id:141, cat:"FRUTA",    name:"Avokado Eat Me Arkë",                                       qty:"4 kg",               price:"2760"},
  {id:142, cat:"FRUTA",    name:"Sallatë Kale",                                              qty:"1 kg",               price:"370"},
  {id:143, cat:"FRUTA",    name:"Sallatë Greke Mix Gjethe",                                  qty:"200 g",              price:"180"},
  {id:144, cat:"FRUTA",    name:"Spinaq Qese Baby Leaves",                                   qty:"100 g",              price:"120"},
  {id:145, cat:"FRUTA",    name:"Fasule Diamond me Thase",                                   qty:"10 kg",              price:"1450"},
  {id:146, cat:"FRUTA",    name:"Rozmarine Vendi",                                           qty:"100 g",              price:"170"},
  {id:147, cat:"FRUTA",    name:"Tumerik",                                                   qty:"1 kg",               price:"750"},
  {id:148, cat:"FRUTA",    name:"Tumerik",                                                   qty:"250 g",              price:"300"},
  {id:149, cat:"FRUTA",    name:"Aviko Patate Wedges Garlic & Herbs",                        qty:"2.5 kg",             price:"780"},
  {id:150, cat:"FRUTA",    name:"Patate Favorita Classic",                                   qty:"1 kg",               price:"220"},
  {id:151, cat:"FRUTA",    name:"Barts Patate SteakHouse Gourmet",                           qty:"2.5 kg",             price:"450"},
  {id:152, cat:"FRUTA",    name:"Barts Patate 10 x 10",                                      qty:"2.5 kg",             price:"450"},
  {id:153, cat:"FRUTA",    name:"Triumph Patate 6x6",                                        qty:"2.5 kg",             price:"425"},
  {id:154, cat:"FRUTA",    name:"LambWeston Patate Dippers",                                 qty:"2.5 kg",             price:"775"},
  {id:155, cat:"FRUTA",    name:"Veggeers Bizele",                                           qty:"20 x 400 g",         price:"125"},
  {id:156, cat:"FRUTA",    name:"Family Perime e Përzier",                                   qty:"900 g",              price:"280"},
  {id:157, cat:"FRUTA",    name:"Polar Misër",                                               qty:"400 g",              price:"155"},
  {id:158, cat:"FRUTA",    name:"Polar Corbu",                                               qty:"400 g",              price:"155"},
  {id:159, cat:"FRUTA",    name:"Polar Bizele",                                              qty:"400 g",              price:"155"},
  {id:160, cat:"FRUTA",    name:"Polar Gjyvec",                                              qty:"400 g",              price:"155"},
  {id:161, cat:"FRUTA",    name:"Polar Sallatë Ruse",                                        qty:"400 g",              price:"155"},
  {id:162, cat:"FRUTA",    name:"Polar Bishtajë e Gjelbërt",                                 qty:"400 g",              price:"155"},
  {id:163, cat:"FRUTA",    name:"Aviko Patate H super crunch 7mm",                           qty:"2.5 kg",             price:"780"},
  {id:164, cat:"FRUTA",    name:"Aviko Patate 10mm",                                         qty:"2.5 kg",             price:"450"},
  {id:165, cat:"FRUTA",    name:"Aviko Patate Steakhouse",                                   qty:"2.5 kg",             price:"700"},
  {id:166, cat:"FRUTA",    name:"Aviko Patate Grip 'n dip",                                  qty:"2 kg",               price:"720"},
  {id:167, cat:"FRUTA",    name:"Aviko Patate Country House 10mm",                           qty:"2.5 kg",             price:"390"},
  {id:168, cat:"FRUTA",    name:"Ginger",                                                    qty:"1 kg",               price:"380"},
  {id:169, cat:"FRUTA",    name:"SELINO",                                                    qty:"1 kg",               price:"250"},
  {id:170, cat:"FRUTA",    name:"SAKURA MIX",                                                qty:"1 kg",               price:"2300"},
  {id:171, cat:"FRUTA",    name:"RRUSH I KUQ IMPORTI",                                       qty:"1 kg",               price:"450"},
  {id:172, cat:"FRUTA",    name:"RUKOLA IMPORTI",                                            qty:"1 kg",               price:"600"},
  {id:173, cat:"FRUTA",    name:"QITRO E KUQE",                                              qty:"1 kg",               price:"210"},
  {id:174, cat:"FRUTA",    name:"QITRO C I BARDHE",                                          qty:"1 kg",               price:"210"},
  {id:175, cat:"FRUTA",    name:"PJEPER",                                                    qty:"1 kg",               price:"145"},
  {id:176, cat:"FRUTA",    name:"NEKTARINA",                                                 qty:"",                   price:"130"},
  {id:177, cat:"FRUTA",    name:"Mjeder",                                                    qty:"125 g",              price:"450"},
  {id:178, cat:"FRUTA",    name:"MANGO IMPORTI (ARKE)",                                      qty:"4 kg",               price:"1680"},
  {id:179, cat:"FRUTA",    name:"Mango Bio",                                                 qty:"1 kg",               price:"1150"},
  {id:180, cat:"FRUTA",    name:"SALAK FRUIT",                                               qty:"",                   price:"2300"},
  {id:181, cat:"FRUTA",    name:"STAR FRUIT",                                                qty:"",                   price:"2300"},
  {id:182, cat:"FRUTA",    name:"MANGOSTAN",                                                 qty:"",                   price:"2300"},
  {id:183, cat:"FRUTA",    name:"Lulelakër",                                                 qty:"1 kg",               price:"140"},
  {id:184, cat:"FRUTA",    name:"MOLLE FUXHI",                                               qty:"1 kg",               price:"150"},
  {id:185, cat:"FRUTA",    name:"MOLLE STRAKINKE",                                           qty:"1 kg",               price:"150"},
  {id:186, cat:"FRUTA",    name:"Laker Brukseli Vaskete",                                    qty:"350 g",              price:"300"},
  {id:187, cat:"FRUTA",    name:"KUMBULL E KUQE",                                            qty:"1 kg",               price:"370"},
  {id:188, cat:"FRUTA",    name:"KUMBULLA TE ZEZA",                                          qty:"1 kg",               price:"370"},
  {id:189, cat:"FRUTA",    name:"KUMBULL E VERDHE",                                          qty:"1 kg",               price:"650"},
  {id:190, cat:"FRUTA",    name:"KERPUDHA PORTOBELLO VASKETE",                               qty:"500 g",              price:"290"},
  {id:191, cat:"FRUTA",    name:"KERPUDHA PLEUROTUS VASKETE",                                qty:"500 g",              price:"290"},
  {id:192, cat:"FRUTA",    name:"KERPUDHA",                                                  qty:"2.5 kg",             price:"925"},
  {id:193, cat:"FRUTA",    name:"KERPUDHA VASKETE",                                          qty:"500 g",              price:"220"},
  {id:194, cat:"FRUTA",    name:"KAJSI",                                                     qty:"1 kg",               price:"150"},
  {id:195, cat:"FRUTA",    name:"FRUT PASIONI",                                              qty:"1 kg",               price:"1200"},
  {id:196, cat:"FRUTA",    name:"Mente",                                                     qty:"Tufë",               price:"140"},
  {id:197, cat:"FRUTA",    name:"Trumez",                                                    qty:"1 kg",               price:"1800"},
  {id:198, cat:"FRUTA",    name:"EREZA TE NJOMA BASIL / BORZILOK",                           qty:"",                   price:"2000"},
  {id:199, cat:"FRUTA",    name:"Erba Cipolina",                                             qty:"Tufë",               price:"200"},
  {id:200, cat:"FRUTA",    name:"DOMATE POMODORINI VASKETE",                                 qty:"500 g",              price:"600"},
  {id:201, cat:"FRUTA",    name:"DOMATE POMODORINI COLOR",                                   qty:"1 kg",               price:"750"},
  {id:202, cat:"FRUTA",    name:"BORONICA EAT ME VASKETE",                                   qty:"",                   price:"260"},
  {id:203, cat:"FRUTA",    name:"AVOKADO KRETA STAR",                                        qty:"1 kg",               price:"380"},
  {id:204, cat:"FRUTA",    name:"Asparag",                                                   qty:"1 kg",               price:"1400"},
  {id:205, cat:"FRUTA",    name:"Arrë Kokosi",                                               qty:"1 kg",               price:"290"},
  {id:206, cat:"FRUTA",    name:"McCain Patate Steakhouse",                                  qty:"2.5 kg",             price:"660"},
  {id:207, cat:"FRUTA",    name:"McCain Patate 9/9",                                         qty:"2.5 kg",             price:"550"},
  {id:208, cat:"FRUTA",    name:"Migro Lenticchie Medie",                                    qty:"500 g",              price:"180"},
  {id:209, cat:"FRUTA",    name:"Borzilok i Grirë ATC",                                      qty:"400 g",              price:"505"},
  {id:210, cat:"FRUTA",    name:"ATC Kripë Himalaje e Zezë e Trashë",                        qty:"500 g",              price:"240"},
  {id:211, cat:"FRUTA",    name:"ATC Timus",                                                 qty:"500 g",              price:"360"},
  {id:212, cat:"FRUTA",    name:"ATC Shafran",                                               qty:"0.6 g",              price:"1008"},
  {id:213, cat:"FRUTA",    name:"ATC Kripë Himalaje e Zezë",                                 qty:"200 g",              price:"180"},
  {id:214, cat:"FRUTA",    name:"ATC Selino e Grirë",                                        qty:"500 g",              price:"590"},
  {id:215, cat:"FRUTA",    name:"ATC Sumak",                                                 qty:"500 g",              price:"1115"},
  {id:216, cat:"FRUTA",    name:"ATC Karafil i Grirë",                                       qty:"500 g",              price:"1140"},
  {id:217, cat:"FRUTA",    name:"ATC Pimento",                                               qty:"500 g",              price:"865"},
  {id:218, cat:"FRUTA",    name:"ATC Mustardë e Grirë",                                      qty:"500 g",              price:"444"},
  {id:219, cat:"FRUTA",    name:"ATC Estragon",                                              qty:"500 g",              price:"1260"},
  {id:220, cat:"FRUTA",    name:"ATC Koriandër Farë",                                        qty:"500 g",              price:"325"},
  {id:221, cat:"FRUTA",    name:"ATC Stevia",                                                qty:"500 g",              price:"1115"},
  {id:222, cat:"FRUTA",    name:"ATC Finok Fara",                                            qty:"500 g",              price:"505"},
  {id:223, cat:"FRUTA",    name:"ATC Kebap Aroma",                                           qty:"500 g",              price:"648"},
  {id:224, cat:"FRUTA",    name:"ATC Piper Gjatosh",                                         qty:"30 g",               price:"215"},
  {id:225, cat:"FRUTA",    name:"ATC Piper Sicuan",                                          qty:"20 g",               price:"306"},
  {id:226, cat:"FRUTA",    name:"ATC Piper i Kuq në Shëllirë",                               qty:"100 g",              price:"576"},
  {id:227, cat:"FRUTA",    name:"ATC Piper Jeshil në Shëllirë",                              qty:"100 g",              price:"216"},
  {id:228, cat:"FRUTA",    name:"ATC Piper Jeshil në Shëllirë",                              qty:"500 g",              price:"1980"},
  {id:229, cat:"FRUTA",    name:"ATC Piper i Kuq në Shëllirë",                               qty:"500 g",              price:"2700"},
  {id:230, cat:"FRUTA",    name:"ATC Farë e Zezë",                                           qty:"430 g",              price:"648"},
  {id:231, cat:"FRUTA",    name:"ATC Fara Liri",                                             qty:"500 g",              price:"216"},
  {id:232, cat:"FRUTA",    name:"ATC Fara Kungulli",                                         qty:"450 g",              price:"505"},
  {id:233, cat:"FRUTA",    name:"ATC Fara Susam i Bardhë",                                   qty:"400 g",              price:"432"},
  {id:234, cat:"FRUTA",    name:"ATC Fara Susam i Zi",                                       qty:"450 g",              price:"432"},
  {id:235, cat:"FRUTA",    name:"ATC Fara Luledielli",                                       qty:"400 g",              price:"180"},
  {id:236, cat:"FRUTA",    name:"ATC Spec Djegës Jumbo",                                     qty:"90 g",               price:"288"},
  {id:237, cat:"FRUTA",    name:"ATC Spec i Kuq i Tymosur i Plotë",                          qty:"420 g",              price:"576"},
  {id:238, cat:"FRUTA",    name:"ATC Kripë aromatike",                                       qty:"655 g",              price:"348"},
  {id:239, cat:"FRUTA",    name:"ATC Xhinxherfill",                                          qty:"230 g",              price:"576"},
  {id:240, cat:"FRUTA",    name:"ATC Shafran Indie",                                         qty:"390 g",              price:"690"},
  {id:241, cat:"FRUTA",    name:"ATC Spec i Kuq Pikant Extra",                               qty:"65 g",               price:"216"},
  {id:242, cat:"FRUTA",    name:"ATC Piper Kokërr Miks",                                     qty:"75 g",               price:"264"},
  {id:243, cat:"FRUTA",    name:"ATC Piper i Zi Kokërr",                                     qty:"85 g",               price:"240"},
  {id:244, cat:"FRUTA",    name:"ATC Rozmarinë Fletë",                                       qty:"500 g",              price:"300"},
  {id:245, cat:"FRUTA",    name:"ATC Vanilje",                                               qty:"500 g",              price:"2088"},
  {id:246, cat:"FRUTA",    name:"ATC Quinoa e Bardhë",                                       qty:"500 g",              price:"480"},
  {id:247, cat:"FRUTA",    name:"ATC Piper i Bardhë i Grirë",                                qty:"500 g",              price:"900"},
  {id:248, cat:"FRUTA",    name:"ATC Stika Pishe",                                           qty:"500 g",              price:"2820"},
  {id:249, cat:"FRUTA",    name:"ATC Fara Susami i Bardhë",                                  qty:"500 g",              price:"384"},
  {id:250, cat:"FRUTA",    name:"ATC Fara Susami i Zi",                                      qty:"500 g",              price:"420"},
  {id:251, cat:"FRUTA",    name:"ATC Borzilok i Grirë",                                      qty:"400 g",              price:"505"},
  {id:252, cat:"FRUTA",    name:"ATC Piper Miks",                                            qty:"500 g",              price:"2160"},
  {id:253, cat:"FRUTA",    name:"ATC Spec i Kuq i Tymosur",                                  qty:"500 g",              price:"756"},
  {id:254, cat:"FRUTA",    name:"ATC Arrë Moskati Kokërr",                                   qty:"500 g",              price:"1656"},
  {id:255, cat:"FRUTA",    name:"ATC Qepë e Grirë",                                          qty:"500 g",              price:"432"},
  {id:256, cat:"FRUTA",    name:"ATC Kumin i Grirë",                                         qty:"500 g",              price:"840"},
  {id:257, cat:"FRUTA",    name:"ATC Piper i Bardhë Kokërr",                                 qty:"500 g",              price:"1070"},
  {id:258, cat:"FRUTA",    name:"ATC Trumëz",                                                qty:"500 g",              price:"300"},
  {id:259, cat:"FRUTA",    name:"ATC Karadamon",                                             qty:"500 g",              price:"5200"},
  {id:260, cat:"FRUTA",    name:"ATC Nenexhik",                                              qty:"400 g",              price:"516"},
  {id:261, cat:"FRUTA",    name:"ATC Majdanoz",                                              qty:"400 g",              price:"768"},
  {id:262, cat:"FRUTA",    name:"ATC Koper Fletë",                                           qty:"500 g",              price:"288"},
  {id:263, cat:"FRUTA",    name:"ATC Farë e Zezë",                                           qty:"500 g",              price:"648"},
  {id:264, cat:"FRUTA",    name:"ATC Piper i Kuq Kokërr",                                    qty:"500 g",              price:"2280"},
  {id:265, cat:"FRUTA",    name:"ATC Qepë Feta",                                             qty:"500 g",              price:"336"},
  {id:266, cat:"FRUTA",    name:"ATC Glikanxo Yll",                                          qty:"500 g",              price:"1620"},
  {id:267, cat:"FRUTA",    name:"ATC Kanellë Shkop Ceylon",                                  qty:"500 g",              price:"2640"},
  {id:268, cat:"FRUTA",    name:"ATC Kanellë Shkop Cassia",                                  qty:"500 g",              price:"1032"},
  {id:269, cat:"FRUTA",    name:"ATC Kanellë e Grirë Cassia",                                qty:"500 g",              price:"540"},
  {id:270, cat:"FRUTA",    name:"Atc Vanilja",                                               qty:"10 g",               price:"216"},
  {id:271, cat:"FRUTA",    name:"Atc Spec i Kuq Pikant i Plote",                             qty:"500 g",              price:"1140"},
  {id:272, cat:"FRUTA",    name:"Atc Rigon",                                                 qty:"500 g",              price:"426"},
  {id:273, cat:"FRUTA",    name:"Atc Quinoa 3 ngjyreshe",                                    qty:"500 g",              price:"690"},
  {id:274, cat:"FRUTA",    name:"Atc Piper i Zi i Grirë",                                    qty:"330 g",              price:"720"},
  {id:275, cat:"FRUTA",    name:"Atc Karafil Gozhde",                                        qty:"500 g",              price:"2100"},
  {id:276, cat:"FRUTA",    name:"Atc Hudher Pluhur",                                         qty:"500 g",              price:"390"},
  {id:277, cat:"FRUTA",    name:"Atc Hudher e Grire",                                        qty:"500 g",              price:"864"},
  {id:278, cat:"FRUTA",    name:"Atc Fara Finoku",                                           qty:"500 g",              price:"530"},
  {id:279, cat:"FRUTA",    name:"Atc Fara Luledielli",                                       qty:"500 g",              price:"180"},
  {id:280, cat:"FRUTA",    name:"Atc Fara Liri",                                             qty:"500 g",              price:"165"},
  {id:281, cat:"FRUTA",    name:"Atc Curry Miks Aromatik",                                   qty:"480 g",              price:"768"},
  {id:282, cat:"FRUTA",    name:"Atc Fara Chia",                                             qty:"530 g",              price:"792"},
  {id:283, cat:"FRUTA",    name:"Atc Borzilok",                                              qty:"150 g",              price:"288"},
  {id:284, cat:"FRUTA",    name:"Atc Arrë Moskat e Grirë",                                   qty:"400 g",              price:"1176"},
  {id:285, cat:"FRUTA",    name:"Atc Arrë Kokosi e Grirë",                                   qty:"500 g",              price:"360"},
  {id:286, cat:"FRUTA",    name:"Atc Stika Pishe",                                           qty:"45 g",               price:"505"},
  {id:287, cat:"FRUTA",    name:"Atc Kripë Himalaje e Jodizuar",                             qty:"400 g",              price:"288"},
  {id:288, cat:"FRUTA",    name:"Atc Kripë Himalaje e jodizuar",                             qty:"200 g",              price:"180"},
  {id:289, cat:"FRUTA",    name:"Atc Fara Kungulli",                                         qty:"500 g",              price:"505"},
  {id:290, cat:"FRUTA",    name:"Atc Dafinë",                                                qty:"50 g",               price:"288"},
  {id:291, cat:"FRUTA",    name:"Atc Spec i Kuq Extra Fara",                                 qty:"500 g",              price:"576"},
  {id:292, cat:"FRUTA",    name:"Atc Spec i Kuq Pikant i Grirë",                             qty:"500 g",              price:"540"},
  {id:293, cat:"FRUTA",    name:"Atc Spec i Kuq i Ëmbël",                                    qty:"500 g",              price:"576"},
  {id:294, cat:"FRUTA",    name:"Atc Shafran Indie",                                         qty:"500 g",              price:"480"},
  {id:295, cat:"FRUTA",    name:"Atc Piper i Zi Kokërr",                                     qty:"500 g",              price:"840"},
  {id:296, cat:"FRUTA",    name:"Atc Piper i Zi i Grirë",                                    qty:"500 g",              price:"810"},
  {id:297, cat:"FRUTA",    name:"Atc Kripë Himalaje e Imët",                                 qty:"500 g",              price:"250"},
  {id:298, cat:"FRUTA",    name:"Atc Kripë Himalaje e Trashë",                               qty:"500 g",              price:"240"},
  {id:299, cat:"FRUTA",    name:"Atc Kanellë e Grirë Ceylon",                                qty:"500 g",              price:"900"},
  {id:300, cat:"FRUTA",    name:"Atc Arrë Moskati e Grirë",                                  qty:"500 g",              price:"1260"},
  {id:301, cat:"FRUTA",    name:"Atc Xhinxherfille e Grirë",                                 qty:"500 g",              price:"480"},
  {id:302, cat:"FRUTA",    name:"Atc Spec i Kuq Pikant i Grirë",                             qty:"350 g",              price:"576"},
  {id:303, cat:"FRUTA",    name:"Atc Spec i Kuq Extra Fara",                                 qty:"280 g",              price:"462"},
  {id:304, cat:"FRUTA",    name:"Atc Spec i Kuq i Ëmbël i Grirë",                            qty:"380 g",              price:"576"},
  {id:305, cat:"FRUTA",    name:"Atc Rigon",                                                 qty:"170 g",              price:"288"},
  {id:306, cat:"FRUTA",    name:"Atc Rozmarinë Fletë",                                       qty:"180 g",              price:"288"},
  {id:307, cat:"FRUTA",    name:"Atc Quinoa",                                                qty:"550 g",              price:"504"},
  {id:308, cat:"FRUTA",    name:"Atc Piper i Zi Kokërr",                                     qty:"400 g",              price:"936"},
  {id:309, cat:"FRUTA",    name:"Atc Piper i Bardhe i Grire",                                qty:"340 g",              price:"1008"},
  {id:310, cat:"FRUTA",    name:"Atc Spec i Kuq Pikant i Plote",                             qty:"160 g",              price:"720"},
  {id:311, cat:"FRUTA",    name:"Atc Nenexhik",                                              qty:"125 g",              price:"288"},
  {id:312, cat:"FRUTA",    name:"Atc Kripë Himalaje",                                        qty:"800 g",              price:"432"},
  {id:313, cat:"FRUTA",    name:"Atc Kanellë e Grirë",                                       qty:"380 g",              price:"756"},
  {id:314, cat:"FRUTA",    name:"Atc Hudher e Grire",                                        qty:"500 g",              price:"590"},
  {id:315, cat:"FRUTA",    name:"Atc Curry Miks Aromatik",                                   qty:"500 g",              price:"414"},
  {id:316, cat:"FRUTA",    name:"Atc Fara Chia",                                             qty:"500 g",              price:"540"},
  {id:317, cat:"FRUTA",    name:"Atc Majdanoz",                                              qty:"105 g",              price:"288"},
  {id:318, cat:"FRUTA",    name:"Atc Piper i Zi Kokërr",                                     qty:"85 g",               price:"240"},
  // ── BULMET ─────────────────────────────────────────────────
  {id:319, cat:"BULMET",   name:"Mozzarella Julienne ( Alimilk )",                            qty:"3 kg",               price:"2340"},
  {id:320, cat:"BULMET",   name:"Mozzarella 40 %",                                           qty:"2.5 kg",             price:"1415"},
  {id:321, cat:"BULMET",   name:"Mozzarella Bufala Alimilk",                                 qty:"12 cop x 250 gr",    price:"4800"},
  {id:322, cat:"BULMET",   name:"Forma PIZZA djathe",                                        qty:"2.5 kg",             price:"825"},
  {id:323, cat:"BULMET",   name:"Gouda 48 % yndyre / origjina : Itali",                      qty:"3.5 kg",             price:"1942"},
  {id:324, cat:"BULMET",   name:"Goudek Djath",                                              qty:"3 kg",               price:"1440"},
  {id:325, cat:"BULMET",   name:"Gouda Djathe 48% yndyre ( Vilvi )",                         qty:"3.5 kg",             price:"1890"},
  {id:326, cat:"BULMET",   name:"Prima Pizza Djathe i bute ( Iliria )",                      qty:"2.5 kg",             price:"850"},
  {id:327, cat:"BULMET",   name:"Nova Pizza djathe i bute ( Iliria )",                       qty:"2.5 kg",             price:"850"},
  {id:328, cat:"BULMET",   name:"Gouda Alpiland",                                            qty:"3 kg",               price:"2550"},
  {id:329, cat:"BULMET",   name:"Kefalotiri Alpiland 45 %",                                  qty:"2 kg",               price:"2840"},
  {id:330, cat:"BULMET",   name:"Gouda Holland",                                             qty:"10 kg",              price:"10350"},
  {id:331, cat:"BULMET",   name:"Gana Italiano Iliria",                                      qty:"200 g",              price:"360"},
  {id:332, cat:"BULMET",   name:"Djathe Blu",                                                qty:"3 kg",               price:"4080"},
  {id:333, cat:"BULMET",   name:"Tostino",                                                   qty:"0.5 kg",             price:"640"},
  {id:334, cat:"BULMET",   name:"Djathe Saganaki Kolios",                                    qty:"3 kg",               price:"3990"},
  {id:335, cat:"BULMET",   name:"Djthe Dele & Dhie Kolios",                                  qty:"0.8 kg",             price:"1480"},
  {id:336, cat:"BULMET",   name:"Dathe dele & dhie Kolios",                                  qty:"12 kg",              price:"18000"},
  {id:337, cat:"BULMET",   name:"Djathe Aspro",                                              qty:"14.5 kg",            price:"8700"},
  {id:338, cat:"BULMET",   name:"Pecorino Tyras",                                            qty:"2 kg",               price:"3680"},
  {id:339, cat:"BULMET",   name:"Kackavall i Tymour",                                        qty:"2 kg",               price:"3200"},
  {id:340, cat:"BULMET",   name:"Kefaloti Tyras",                                            qty:"2 kg",               price:"2840"},
  {id:341, cat:"BULMET",   name:"Djathe Lope Ageladino",                                     qty:"15 kg",              price:"11250"},
  {id:342, cat:"BULMET",   name:"d.Lope Perla",                                              qty:"15 kg",              price:"9750"},
  {id:343, cat:"BULMET",   name:"- || - Perla",                                              qty:"4 kg",               price:"3240"},
  {id:344, cat:"BULMET",   name:"Tyras djathe dhie",                                         qty:"4 kg",               price:"1170"},
  {id:345, cat:"BULMET",   name:"krem djath",                                                qty:"2 kg",               price:"1400"},
  {id:346, cat:"BULMET",   name:"djathe i grire 3 Mix",                                      qty:"100 gr",             price:"85"},
  {id:347, cat:"BULMET",   name:"Tyras djathe lope i prere",                                 qty:"10 kg",              price:"7800"},
  {id:348, cat:"BULMET",   name:"Djathe Emmental Bavarese 2.5 kg",                           qty:"2.5 kg",             price:"2450"},
  {id:349, cat:"BULMET",   name:"Grana padano Dop",                                          qty:"5 kg",               price:"7750"},
  {id:350, cat:"BULMET",   name:"Grana retianata",                                           qty:"4.5 kg",             price:"5805"},
  {id:351, cat:"BULMET",   name:"Djathe Duro Forcello",                                      qty:"5 kg",               price:"6000"},
  {id:352, cat:"BULMET",   name:"Djathe Cedar",                                              qty:"3.3 kg",             price:"3795"},
  {id:353, cat:"BULMET",   name:"Prima Djathe Lope",                                         qty:"10 kg",              price:"7800"},
  {id:354, cat:"BULMET",   name:"Gjalpe gourmet Panetti",                                    qty:"1 kg",               price:"980"},
  {id:355, cat:"BULMET",   name:"Dijamant Gjalp i Tretur",                                   qty:"4.8 kg",             price:"2040"},
  {id:356, cat:"BULMET",   name:"Butter Dreams Gjalp 10 kg",                                 qty:"10 kg",              price:"3000"},
  {id:357, cat:"BULMET",   name:"Zolovata Margarine 82 %",                                   qty:"5 kg",               price:"2000"},
  {id:358, cat:"BULMET",   name:"Capri Margarine 82 %",                                      qty:"5 kg",               price:"3000"},
  {id:359, cat:"BULMET",   name:"Ghidetti Mascarpone",                                       qty:"0.5 kg",             price:"550"},
  // ── MISH I BARDHE ──────────────────────────────────────────
  {id:360, cat:"MISHB",    name:"Krahe Pule i Verdhe Prime",                                  qty:"10 kg",              price:"2900"},
  {id:361, cat:"MISHB",    name:"Kotolete e Vogel 6 kg + Kotolet e Madhe 5 kg",              qty:"6 kg + 5 kg",        price:"5990"},
  {id:362, cat:"MISHB",    name:"Fileto Pule Turke",                                         qty:"2 kg",               price:"960"},
  {id:363, cat:"MISHB",    name:"Fileto Pule Copacol",                                       qty:"2 kg",               price:"680"},
  {id:364, cat:"MISHB",    name:"Kofshe Pule Small",                                         qty:"15 kg",              price:"2850"},
  {id:365, cat:"MISHB",    name:"Krah Pule i Verdhe Mid",                                    qty:"10 kg",              price:"2900"},
  {id:366, cat:"MISHB",    name:"Kotoleta te Medha",                                         qty:"5 kg",               price:"3720"},
  {id:367, cat:"MISHB",    name:"Kotoleta te Vogla",                                         qty:"6 kg",               price:"3100"},
  {id:368, cat:"MISHB",    name:"Chicken Fingers ( Lezita )",                                qty:"1 kg",               price:"800"},
  {id:369, cat:"MISHB",    name:"Fileto Pule krokante ( Lezita )",                           qty:"0.7 kg",             price:"570"},
  {id:370, cat:"MISHB",    name:"Fileto Pule e ngrirre",                                     qty:"0.9 kg",             price:"420"},
  // ── MISH I PERPUNUAR ───────────────────────────────────────
  {id:371, cat:"MISHP",    name:"Proshute Vici Shufer",                                       qty:"2.5 kg",             price:"1500"},
  {id:372, cat:"MISHP",    name:"Proshute Pule Shufer",                                       qty:"2.5 kg",             price:"1500"},
  {id:373, cat:"MISHP",    name:"Sallam Milano i prere",                                      qty:"0.5 kg",             price:"330"},
  {id:374, cat:"MISHP",    name:"Proshute pule e prere",                                      qty:"0.5 kg",             price:"290"},
  {id:375, cat:"MISHP",    name:"Proshute Vici e prere",                                      qty:"0.5 kg",             price:"300"},
  {id:376, cat:"MISHP",    name:"Sallam Berlin i prere",                                      qty:"0.5 kg",             price:"300"},
  {id:377, cat:"MISHP",    name:"Sallam pikant i prere",                                      qty:"0.5 kg",             price:"300"},
  {id:378, cat:"MISHP",    name:"Kremvice pule",                                              qty:"1 kg",               price:"390"},
  {id:379, cat:"MISHP",    name:"Sallam Parizier i prere",                                    qty:"0.5 kg",             price:"170"},
  {id:380, cat:"MISHP",    name:"Kremvice speciale",                                          qty:"1 kg",               price:"650"},
  {id:381, cat:"MISHP",    name:"Kremvice e tymosur",                                         qty:"1 kg",               price:"430"},
  {id:382, cat:"MISHP",    name:"Salcice Pule",                                               qty:"1 kg",               price:"420"},
  {id:383, cat:"MISHP",    name:"Prosciutto Cotto 1/2 S.viglio",                              qty:"5 kg",               price:"3250"},
  {id:384, cat:"MISHP",    name:"Guanciale Stag Al Pepe",                                     qty:"1 kg",               price:"1250"},
  {id:385, cat:"MISHP",    name:"Merlotti Salame",                                            qty:"1.2 kg",             price:"1500"},
  {id:386, cat:"MISHP",    name:"Spianata piccante",                                          qty:"1 kg",               price:"1250"},
  {id:387, cat:"MISHP",    name:"salsiccia piccante dritta",                                  qty:"1 kg",               price:"1250"},
  {id:388, cat:"MISHP",    name:"Prosciutto Crudo Staggionato",                               qty:"6 kg",               price:"9300"},
  {id:389, cat:"MISHP",    name:"Bresaola Sv",                                                qty:"1.2 kg",             price:"3480"},
  {id:390, cat:"MISHP",    name:"Mortadella Ermes Fontana",                                   qty:"3 kg",               price:"2250"},
  {id:391, cat:"MISHP",    name:"Prosciutto Crudo Cerreto Menatti",                           qty:"7.5 kg",             price:"12375"},
  {id:392, cat:"MISHP",    name:"Nduija piccante",                                            qty:"0.3 kg",             price:"540"},
  {id:393, cat:"MISHP",    name:"Speck",                                                      qty:"3 kg",               price:"3600"},
  {id:394, cat:"MISHP",    name:"Prosciutto Cotto Sgrassato",                                 qty:"4 kg",               price:"2640"},
  {id:395, cat:"MISHP",    name:"Pancetta stufata bacon",                                     qty:"6 kg",               price:"5700"},
  {id:396, cat:"MISHP",    name:"Pastrami bovino",                                            qty:"2.5 kg",             price:"4625"},
  {id:397, cat:"MISHP",    name:"Capocollo S/V",                                              qty:"1 kg",               price:"1900"},
  {id:398, cat:"MISHP",    name:"Dimal Kernacka Speciale",                                    qty:"1 x 8 cop",          price:"152"},
  {id:399, cat:"MISHP",    name:"Dimal Qebap",                                                qty:"1 x 8",              price:"184"},
  {id:400, cat:"MISHP",    name:"Dimal Qofte Pule",                                           qty:"1 x 8",              price:"152"},
  {id:401, cat:"MISHP",    name:"Dimal Hamburger",                                            qty:"1 x 8",              price:"152"},
  {id:402, cat:"MISHP",    name:"Nduija Piccante 5+ 1 falas",                                 qty:"1 x 8",              price:"2700"},
  // ── MISH I KUQ ─────────────────────────────────────────────
  {id:403, cat:"MISHK",    name:"Rosto Vici",                                                 qty:"1 kg",               price:"1000"},
  {id:404, cat:"MISHK",    name:"Rosto Vici",                                                 qty:"5+ kg",              price:"4750"},
  // ── PRODUKTE MISHI & PESHKU ────────────────────────────────
  {id:405, cat:"PESHKU",   name:"FISH STICKS",                                               qty:"5 copë + 1 falas",   price:""},
  {id:406, cat:"PESHKU",   name:"Lezita Fileto Pule me Drithëra",                            qty:"700 g",              price:"570"},
  {id:407, cat:"PESHKU",   name:"Kotoleta Pule",                                             qty:"1 kg",               price:"520"},
  {id:408, cat:"PESHKU",   name:"Fileto Merluci Pane",                                       qty:"250 g",              price:"390"},
  {id:409, cat:"PESHKU",   name:"FISH STICKS (PA GLUTEN)",                                   qty:"300 g",              price:"390"},
  {id:410, cat:"PESHKU",   name:"Salsiccia Fresca Norcia Lanzi",                             qty:"500 g",              price:"600"},
  {id:411, cat:"PESHKU",   name:"Orion Fileto Pule e Ngrirë",                                qty:"900 g",              price:"420"},
  {id:412, cat:"PESHKU",   name:"Siblou Karkaleca Suprem",                                   qty:"500 g",              price:"1166"},
  {id:413, cat:"PESHKU",   name:"Siblou Fruta Deti",                                         qty:"500 g",              price:"869"},
  {id:414, cat:"PESHKU",   name:"Siblou Karkaleca të Gatuar",                                qty:"500 g",              price:"1166"},
  {id:415, cat:"PESHKU",   name:"Siblou Fileto Peshku e Bardhë",                             qty:"1 kg",               price:"650"},
  {id:416, cat:"PESHKU",   name:"Lezita Rrathë Pule Krokant",                                qty:"400 g",              price:"300"},
  {id:417, cat:"PESHKU",   name:"Lezita Kotoleta Pule",                                      qty:"500 g",              price:"270"},
  // ── BRUME & EMBELSIRA ──────────────────────────────────────
  {id:418, cat:"BRUME",    name:"Buke Tost",                                                  qty:"0,75 kg",            price:""},
  {id:419, cat:"BRUME",    name:"Basket Cornflex",                                            qty:"5cp x 0.7 kg",       price:""},
  {id:420, cat:"BRUME",    name:"Buke Masive",                                                qty:"10 cp x 0.7 kg",     price:"800"},
  {id:421, cat:"BRUME",    name:"Basket Multigrain",                                          qty:"",                   price:""},
  {id:422, cat:"BRUME",    name:"Baguette Rustic",                                            qty:"",                   price:""},
  {id:423, cat:"BRUME",    name:"Panine Barbeque",                                            qty:"",                   price:""},
  {id:424, cat:"BRUME",    name:"Panine Multigrain",                                          qty:"",                   price:""},
  {id:425, cat:"BRUME",    name:"Panine Cornflex",                                            qty:"",                   price:""},
  {id:426, cat:"BRUME",    name:"Ciabatta Multigrain",                                        qty:"",                   price:""},
  {id:427, cat:"BRUME",    name:"Ciabatta Sunloaf",                                           qty:"",                   price:""},
  {id:428, cat:"BRUME",    name:"Mini Multigrain",                                            qty:"",                   price:""},
  {id:429, cat:"BRUME",    name:"Burger Buns",                                                qty:"",                   price:""},
  {id:430, cat:"BRUME",    name:"Buke pirati pikante",                                        qty:"",                   price:"800"},
  {id:431, cat:"BRUME",    name:"Buke pirati 25 % Vaj Ulliri",                                qty:"",                   price:"800"},
  {id:432, cat:"BRUME",    name:"Buke Pirati me ullinj",                                      qty:"",                   price:"800"},
  {id:433, cat:"BRUME",    name:"Buke Pirati me Domate te thata",                             qty:"",                   price:"800"},
  {id:434, cat:"BRUME",    name:"Pite",                                                       qty:"",                   price:""},
  {id:435, cat:"BRUME",    name:"Kolios Pocket pita 19 cm",                                   qty:"5 cp x 90g",         price:"150"},
  {id:436, cat:"BRUME",    name:"Samati Pite te bera me Dore",                                qty:"10 cop",             price:"190"},
  {id:437, cat:"BRUME",    name:"Elviart Pita Autentike",                                     qty:"8 cp x 16cm",        price:"155"},
  {id:438, cat:"BRUME",    name:"Mini Sunloaf",                                               qty:"50cp x 50 g",        price:"750"},
  {id:439, cat:"BRUME",    name:"Mini Barbeque",                                              qty:"50cp x 50 g",        price:"950"},
  {id:440, cat:"BRUME",    name:"Mini Olivea",                                                qty:"50cp x 50 g",        price:"950"},
  {id:441, cat:"BRUME",    name:"Mini Rosso",                                                 qty:"50cp x 50 g",        price:"950"},
  {id:442, cat:"BRUME",    name:"Baguette Sunloaf",                                           qty:"20 x 270 g",         price:"1200"},
  {id:443, cat:"BRUME",    name:"Mini Cornflex",                                              qty:"50cp x 50 g",        price:"950"},
  {id:444, cat:"BRUME",    name:"Burger Buns",                                                qty:"60 copë x 110 g",    price:""},
  {id:445, cat:"BRUME",    name:"Briosh Krem Pastiçerie XL",                                  qty:"10cp x 115 g",       price:"850"},
  {id:446, cat:"BRUME",    name:"Briosh Pistak XL",                                           qty:"10cp x 115 g",       price:"950"},
  {id:447, cat:"BRUME",    name:"Briosh Çokollatë XL",                                        qty:"10cp x 115 g",       price:"850"},
  {id:448, cat:"BRUME",    name:"Bougatsa me Krem",                                           qty:"500 g",              price:"330"},
  {id:449, cat:"BRUME",    name:"Briosh Parisien Krem Pastiçerie",                            qty:"10cp x 60 g",        price:"800"},
  {id:450, cat:"BRUME",    name:"Briosh Premium Krem Pastiçerie",                             qty:"10cp x 110 g",       price:"1200"},
  {id:451, cat:"BRUME",    name:"Alfa Kruasant Mini me Çokollatë",                            qty:"10cp x 33 g",        price:"300"},
  // ── SNACK & USHQIME TE SHPEJTA ─────────────────────────────
  {id:452, cat:"SNACK",    name:"Mix Sandwich-e",                                             qty:"14 copë (7 shije x 2 copë)", price:"2300"},
  {id:453, cat:"SNACK",    name:"Tramezzini Mix",                                             qty:"6cp",                price:"720"},
  {id:454, cat:"SNACK",    name:"Kikirik i Presuar Palma",                                    qty:"500 gr",             price:"370"},
  {id:455, cat:"SNACK",    name:"Sandwich Mortadella",                                        qty:"",                   price:"1020"},
  {id:456, cat:"SNACK",    name:"Cocktail Snak",                                              qty:"1 kg",               price:"580"},
  {id:457, cat:"SNACK",    name:"Tramezzini Proshutë Viçi",                                   qty:"",                   price:"120"},
  {id:458, cat:"SNACK",    name:"Sandwich me Proshutë Gjeli",                                 qty:"",                   price:"960"},
  {id:459, cat:"SNACK",    name:"Tramezzini Proshutë Pule",                                   qty:"",                   price:"120"},
  {id:460, cat:"SNACK",    name:"Sandwich Vegjetarian",                                       qty:"",                   price:"900"},
  {id:461, cat:"SNACK",    name:"El Sabor Chilli",                                            qty:"425 gr",             price:"360"},
  {id:462, cat:"SNACK",    name:"Tramezzini Mortadella",                                      qty:"",                   price:"120"},
  {id:463, cat:"SNACK",    name:"El Sabor Cheese",                                            qty:"425 gr",             price:"340"},
  {id:464, cat:"SNACK",    name:"Sandwich Bresaola",                                          qty:"",                   price:"1020"},
  {id:465, cat:"SNACK",    name:"Jumbo Tortilla Cheese",                                      qty:"350 gr",             price:"280"},
  {id:466, cat:"SNACK",    name:"Sandwich Pikant",                                            qty:"",                   price:"1020"},
  {id:467, cat:"SNACK",    name:"Jumbo Tortilla Chilli",                                      qty:"350 gr",             price:"280"},
  {id:468, cat:"SNACK",    name:"Sandwich Milanez",                                           qty:"",                   price:"960"},
  {id:469, cat:"SNACK",    name:"El Sabor Jalapeno",                                          qty:"425 gr",             price:"320"},
  {id:470, cat:"SNACK",    name:"Toast Mortadella",                                           qty:"6cp",                price:"600"},
  {id:471, cat:"SNACK",    name:"Toast Proshutë Pule",                                        qty:"6cp",                price:"600"},
  {id:472, cat:"SNACK",    name:"Toast Proshutë Vici",                                        qty:"6cp",                price:"600"},
  {id:473, cat:"SNACK",    name:"Sandwich Pastrami",                                          qty:"",                   price:"1020"},
  {id:474, cat:"SNACK",    name:"Mozzarella Stick",                                           qty:"1 kg",               price:"1300"},
  {id:475, cat:"SNACK",    name:"Bono Çokollatë",                                             qty:"20cp x 80 g",        price:"940"},
  {id:476, cat:"SNACK",    name:"Bono Qershi",                                                qty:"20cp x 80 g",        price:"940"},
  {id:477, cat:"SNACK",    name:"Bono me Qumësht dhe Çokollatë",                              qty:"20cp x 80 g",        price:"1240"},
  {id:478, cat:"SNACK",    name:"Bono Luleshtrydhe",                                          qty:"20cp x 80 g",        price:"940"},
  {id:479, cat:"SNACK",    name:"Bono Kajsi",                                                 qty:"20cp x 80 g",        price:"940"},
  {id:480, cat:"SNACK",    name:"Bono Pistak",                                                qty:"20cp x 80 g",        price:"1100"},
  {id:481, cat:"SNACK",    name:"Bono Vanilje",                                               qty:"20cp x 80 g",        price:"940"},
  {id:482, cat:"SNACK",    name:"Bono Lajthi",                                                qty:"20cp x 80 g",        price:"940"},
  {id:483, cat:"SNACK",    name:"Bono me Mjaltë dhe Fruta",                                   qty:"20cp x 80 g",        price:"1100"},
  {id:484, cat:"SNACK",    name:"Mr. Croquette Kroketa Patatesh me Presh dhe Qepë",           qty:"1 kg",               price:"600"},
  {id:485, cat:"SNACK",    name:"Mr. Croquette Qofte me Perime Miks",                         qty:"500 g",              price:"340"},
  {id:486, cat:"SNACK",    name:"Mr. Croquette Qofte Vegjetariane me Domate",                 qty:"500 gr",             price:"400"},
  {id:487, cat:"SNACK",    name:"Mr. Croquette Qofte Vegjetariane me Kungull",                qty:"500 g",              price:"400"},
  {id:488, cat:"SNACK",    name:"Mr. Corquette Kroketa me Djathë",                            qty:"500 g",              price:"420"},
  {id:489, cat:"SNACK",    name:"Mr. Croquette Spring Rolls me Perime",                       qty:"500 g",              price:"350"},
  {id:490, cat:"SNACK",    name:"McCain Onion Rings",                                         qty:"1 kg",               price:"599"},
  {id:491, cat:"SNACK",    name:"Barts Chili Cheese Nuggets",                                 qty:"1 kg",               price:"1100"},
  {id:492, cat:"SNACK",    name:"LambWeston Onion Ring",                                      qty:"1 kg",               price:"480"},
  {id:493, cat:"SNACK",    name:"Aviko Breaded Onion Rings",                                  qty:"1 kg",               price:"540"},
  // ── SALCA ──────────────────────────────────────────────────
  {id:494, cat:"SALCA",    name:"Casillo Pelati di pomodori",                                 qty:"2.5 kg",             price:"550"},
  {id:495, cat:"SALCA",    name:"Ponti Pesto genovese",                                       qty:"530 gr",             price:"570"},
  {id:496, cat:"SALCA",    name:"Barilla pesto genovese",                                     qty:"190gr",              price:"240"},
  {id:497, cat:"SALCA",    name:"barilla sugo basilico",                                      qty:"400 gr",             price:"185"},
  {id:498, cat:"SALCA",    name:"barilla sugo arrabiata",                                     qty:"400 gr",             price:"185"},
  {id:499, cat:"SALCA",    name:"divella passata",                                            qty:"680 gr",             price:"120"},
  {id:500, cat:"SALCA",    name:"barilla pesto siciliano",                                    qty:"190 gr",             price:"240"},
  {id:501, cat:"SALCA",    name:"la salse crema tartufo",                                     qty:"520 gr",             price:"750"},
  {id:502, cat:"SALCA",    name:"barilla pesto calabrese",                                    qty:"190 gr",             price:"240"},
  {id:503, cat:"SALCA",    name:"mutti passata bottiglia",                                    qty:"700 ml",             price:"160"},
  {id:504, cat:"SALCA",    name:"mutti passata basilico",                                     qty:"700 ml",             price:"200"},
  {id:505, cat:"SALCA",    name:"cirio passata rustica",                                      qty:"680 gr",             price:"150"},
  {id:506, cat:"SALCA",    name:"barilla sugo amatricana",                                    qty:"680 gr",             price:"180"},
  {id:507, cat:"SALCA",    name:"calve",                                                      qty:"450 ml",             price:"230"},
  {id:508, cat:"SALCA",    name:"salc kosi vital",                                            qty:"5 kg",               price:"1325"},
  {id:509, cat:"SALCA",    name:"salc kosi vital",                                            qty:"1 kg",               price:"270"},
  {id:510, cat:"SALCA",    name:"salc kosi perla",                                            qty:"5 k g",              price:"1250"},
  {id:511, cat:"SALCA",    name:"salc kosi perla",                                            qty:"900 gr",             price:"250"},
  {id:512, cat:"SALCA",    name:"paste domateje",                                             qty:"5 kg",               price:"2175"},
  {id:513, cat:"SALCA",    name:"paste domateje",                                             qty:"350 gr",             price:"210"},
  {id:514, cat:"SALCA",    name:"majonez CALVE",                                              qty:"5 kg",               price:""},
  {id:515, cat:"SALCA",    name:"HEINZ Majoneze",                                             qty:"5 kg",               price:"1750"},
  {id:516, cat:"SALCA",    name:"majonez Avance",                                             qty:"5 kg",               price:"850"},
  {id:517, cat:"SALCA",    name:"mustard iliria",                                             qty:"5 kg",               price:"870"},
  {id:518, cat:"SALCA",    name:"ketchup iliria",                                             qty:"5 kg",               price:"680"},
  {id:519, cat:"SALCA",    name:"majonez iliria",                                             qty:"5 kg",               price:"1500"},
  {id:520, cat:"SALCA",    name:"mustard iliria",                                             qty:"4 kg",               price:"700"},
  {id:521, cat:"SALCA",    name:"ketchup iliria",                                             qty:"4 kg",               price:"550"},
  {id:522, cat:"SALCA",    name:"speca me salce iliia",                                       qty:"5 kg",               price:"1250"},
  {id:523, cat:"SALCA",    name:"Ketchup Paltsidis",                                          qty:"4 kg",               price:"750"},
  {id:524, cat:"SALCA",    name:"Desantis Polpa",                                             qty:"4 kg",               price:"750"},
  {id:525, cat:"SALCA",    name:"Krem Tartufi",                                               qty:"580 ml",             price:"900"},
  {id:526, cat:"SALCA",    name:"Pesto Pistacchio",                                           qty:"500 gr",             price:"1900"},
  // ── PASTA ──────────────────────────────────────────────────
  {id:527, cat:"PASTA",    name:"Barilla fusili 098",                                         qty:"500 gr",             price:"95"},
  {id:528, cat:"PASTA",    name:"Garofalo Penne Rigate",                                      qty:"500 gr",             price:"140"},
  {id:529, cat:"PASTA",    name:"De cecco fusilli",                                           qty:"500 gr",             price:"150"},
  {id:530, cat:"PASTA",    name:"barilla risoni 026",                                         qty:"500 gr",             price:"95"},
  {id:531, cat:"PASTA",    name:"de cecco rigatoni",                                          qty:"500 gr",             price:"150"},
  {id:532, cat:"PASTA",    name:"Armando Fusilio",                                            qty:"500 gr",             price:"130"},
  {id:533, cat:"PASTA",    name:"Armando la Linguine",                                        qty:"500 gr",             price:"130"},
  {id:534, cat:"PASTA",    name:"Armando L'orecchieta",                                       qty:"500 gr",             price:"130"},
  {id:535, cat:"PASTA",    name:"Armando penne rigate",                                       qty:"500 gr",             price:"130"},
  {id:536, cat:"PASTA",    name:"Armando La Spaghettone",                                     qty:"500 gr",             price:"130"},
  {id:537, cat:"PASTA",    name:"Armando paccheri",                                           qty:"500 gr",             price:"230"},
  {id:538, cat:"PASTA",    name:"rummo rigatoni",                                             qty:"500 gr",             price:"120"},
  {id:539, cat:"PASTA",    name:"Rummo fusilli",                                              qty:"500 gr",             price:"120"},
  {id:540, cat:"PASTA",    name:"Rummo Spaghetti",                                            qty:"500 gr",             price:"120"},
  {id:541, cat:"PASTA",    name:"De cecco linguine 007",                                      qty:"500 gr",             price:"144"},
  {id:542, cat:"PASTA",    name:"de cecco spaghetti 012",                                     qty:"500 gr",             price:"150"},
  {id:543, cat:"PASTA",    name:"barilla spaghetti nr.3",                                     qty:"500 gr",             price:"95"},
  {id:544, cat:"PASTA",    name:"barilla vermicelli",                                         qty:"500 gr",             price:"95"},
  {id:545, cat:"PASTA",    name:"barilla gnocchi",                                            qty:"500 gr",             price:"95"},
  {id:546, cat:"PASTA",    name:"barilla bavete linguine",                                    qty:"500 gr",             price:"95"},
  {id:547, cat:"PASTA",    name:"garofalo linguine",                                          qty:"500 gr",             price:"140"},
  {id:548, cat:"PASTA",    name:"garofalo fusili",                                            qty:"500 gr",             price:"140"},
  {id:549, cat:"PASTA",    name:"garofalo spaghetti",                                         qty:"500 gr",             price:"140"},
  // ── ORIZ ───────────────────────────────────────────────────
  {id:550, cat:"ORIZ",     name:"Oriz Teuta Gold blu",                                        qty:"1 kg",               price:"190"},
  {id:551, cat:"ORIZ",     name:"Oriz Teuta Gold jeshil",                                     qty:"1kg",                price:"180"},
  {id:552, cat:"ORIZ",     name:"Oriz gold Lotto",                                            qty:"1 kg",               price:"170"},
  {id:553, cat:"ORIZ",     name:"Riseria Peila Riso Paraboiled",                              qty:"10 cp x 1 kg",       price:"2300"},
  {id:554, cat:"ORIZ",     name:"Riseria Peila Riso Paraboiled",                              qty:"5 kg",               price:"970"},
  {id:555, cat:"ORIZ",     name:"Diamond Oriz Verona",                                        qty:"1 kg",               price:"170"},
  {id:556, cat:"ORIZ",     name:"Diamond Oriz Extra",                                         qty:"1 kg",               price:"160"},
  {id:557, cat:"ORIZ",     name:"Riseria Peila Carnaroli rizoto",                             qty:"5 x 1 kg",           price:"340"},
  {id:558, cat:"ORIZ",     name:"scotti carnaroli",                                           qty:"5 x 1 kg",           price:"1750"},
  {id:559, cat:"ORIZ",     name:"scotti arborio",                                             qty:"5 x 1 kg",           price:"1680"},
  {id:560, cat:"ORIZ",     name:"scotti food service",                                        qty:"5 x 1 kg",           price:"1020"},
  {id:561, cat:"ORIZ",     name:"scotti ribe paraboiled",                                     qty:"5 x 1 kg",           price:"980"},
  {id:562, cat:"ORIZ",     name:"scotti riso venere",                                         qty:"5 x 1 kg",           price:"2750"},
  // ── PIJE FRESKUESE ─────────────────────────────────────────
  {id:563, cat:"PIJE",     name:"Kanaçe ( cola / fanta / sprite )",                           qty:"5+ koli",            price:"52 L/cp"},
  {id:564, cat:"PIJE",     name:"Kanaçe ( cola / fanta / sprite )",                           qty:"1 koli",             price:"55 L/cp"},
  {id:565, cat:"PIJE",     name:"Pepsi",                                                      qty:"5+ koli",            price:"42 L/cp"},
  {id:566, cat:"PIJE",     name:"Pepsi",                                                      qty:"3+ koli",            price:"45 L/cp"},
  {id:567, cat:"PIJE",     name:"Pepsi",                                                      qty:"1 koli",             price:"50 L/cp"},
  {id:568, cat:"PIJE",     name:"Ivi",                                                        qty:"1 koli",             price:"52 L/cp"},
  {id:569, cat:"PIJE",     name:"Lemon soda",                                                 qty:"1 koli",             price:"62 L/cp"},
  {id:570, cat:"PIJE",     name:"Lemonade Rose ( shishe )",                                   qty:"12cp x 275 ml",      price:"204 L/cp"},
  {id:571, cat:"PIJE",     name:"Lemonade Rose ( kanace )",                                   qty:"24cp x 250 ml",      price:"145 L/cp"},
  {id:572, cat:"PIJE",     name:"Britvic Tonic water",                                        qty:"24 cp x 150 ml",     price:"53 L/cp"},
  {id:573, cat:"PIJE",     name:"Pacha Drink",                                                qty:"1 koli",             price:"82 L/cp"},
  {id:574, cat:"PIJE",     name:"Aranxhata",                                                  qty:"1 koli",             price:"58 L/cp"},
  {id:575, cat:"PIJE",     name:"bitter",                                                     qty:"24cp x 125 ml",      price:"37.5 L/cp"},
  {id:576, cat:"PIJE",     name:"amita ( me pipe )",                                          qty:"5+ koli",            price:"57 L/cp"},
  {id:577, cat:"PIJE",     name:"amita ( me pipe )",                                          qty:"1 koli",             price:"60 L/cp"},
  {id:578, cat:"PIJE",     name:"amita ( me tape )",                                          qty:"5+ koli",            price:"66 L/cp"},
  {id:579, cat:"PIJE",     name:"amita ( me tape )",                                          qty:"10+ koli",           price:"64 L/cp"},
  {id:580, cat:"PIJE",     name:"amita ( me tape )",                                          qty:"1 koi",              price:"68 L/cp"},
  {id:581, cat:"PIJE",     name:"bravo",                                                      qty:"1 koli",             price:"65 L/cp"},
  {id:582, cat:"PIJE",     name:"Lipton",                                                     qty:"5+ koli",            price:"45 L/cp"},
  {id:583, cat:"PIJE",     name:"Lipton",                                                     qty:"1 koli",             price:"50 L/cp"},
  {id:584, cat:"PIJE",     name:"santal",                                                     qty:"24 cp x 250 ml",     price:"114.5 L/cp"},
  // ── UJE ────────────────────────────────────────────────────
  {id:585, cat:"UJE",      name:"Lajthiza",                                                   qty:"20koli + 1 koli falas", price:"6400"},
  {id:586, cat:"UJE",      name:"Glina Limon",                                                qty:"",                   price:""},
  {id:587, cat:"UJE",      name:"Glina",                                                      qty:"",                   price:""},
  {id:588, cat:"UJE",      name:"qafshtama",                                                  qty:"",                   price:""},
  {id:589, cat:"UJE",      name:"Acqua Panna",                                                qty:"",                   price:""},
  {id:590, cat:"UJE",      name:"san pelegrino",                                              qty:"",                   price:""},
  {id:591, cat:"UJE",      name:"selita",                                                     qty:"",                   price:""},
  {id:592, cat:"UJE",      name:"selita me gaz",                                              qty:"",                   price:""},
  // ── BIRRA ──────────────────────────────────────────────────
  {id:593, cat:"BIRRA",    name:"Peroni",                                                     qty:"5+ koli",            price:"82 L/cp"},
  {id:594, cat:"BIRRA",    name:"Peroni",                                                     qty:"3+ koli",            price:"83 L/cp"},
  {id:595, cat:"BIRRA",    name:"peroni",                                                     qty:"1 koli",             price:"85 L/cp"},
  {id:596, cat:"BIRRA",    name:"peroni nastro azzuro",                                       qty:"5+ koli",            price:"95 L/cp"},
  {id:597, cat:"BIRRA",    name:"peroni nastro azzuro",                                       qty:"3+ koli",            price:"97 L/cp"},
  {id:598, cat:"BIRRA",    name:"peroni nastro azzuro",                                       qty:"1 koli",             price:"100 L/cp"},
  {id:599, cat:"BIRRA",    name:"peroni Italian",                                             qty:"1 koli",             price:"88 L/cp"},
  {id:600, cat:"BIRRA",    name:"peroni kanace",                                              qty:"3+ koli (330ml)",    price:"65 L/cp"},
  {id:601, cat:"BIRRA",    name:"Corona",                                                     qty:"1 koli",             price:"110 L/cp"},
  {id:602, cat:"BIRRA",    name:"corona 355ml",                                               qty:"1 koli",             price:"110 L/cp"},
  {id:603, cat:"BIRRA",    name:"Bavaria pa alkool shishe",                                   qty:"24 x 330 ml",        price:"84 L/cp"},
  {id:604, cat:"BIRRA",    name:"Bavaria pa alkool kanace",                                   qty:"24 x 500 ml",        price:"85 L/cp"},
  {id:605, cat:"BIRRA",    name:"paulaner kristal",                                           qty:"20 cp x 500 ml",     price:"150 L/cp"},
  {id:606, cat:"BIRRA",    name:"paulaner i turbullt",                                        qty:"20 cp x 500 ml",     price:"140 L/cp"},
  {id:607, cat:"BIRRA",    name:"erdinger i turbullt",                                        qty:"12 cp x 500 ml",     price:"185 L/cp"},
  {id:608, cat:"BIRRA",    name:"erdinger kristal",                                           qty:"12 cp x 500 ml",     price:"185 L/cp"},
  {id:609, cat:"BIRRA",    name:"paulaner kristal - kanace",                                  qty:"24 cp x 500 ml",     price:"104 L/cp"},
  {id:610, cat:"BIRRA",    name:"heineken shishe",                                            qty:"5+ koli",            price:"95 L/cp"},
  {id:611, cat:"BIRRA",    name:"heineken shishe",                                            qty:"3+ koli",            price:"96 L/cp"},
  {id:612, cat:"BIRRA",    name:"heineken shishe",                                            qty:"1 koli",             price:"102 L/cp"},
  {id:613, cat:"BIRRA",    name:"heineken italian",                                           qty:"1 koli",             price:"100 L/cp"},
  {id:614, cat:"BIRRA",    name:"heineken kanace",                                            qty:"5+ arka ( 330 ml )", price:"80 L/cp"},
  {id:615, cat:"BIRRA",    name:"heineken kanace",                                            qty:"3+ arka",            price:"85 L/cp"},
  {id:616, cat:"BIRRA",    name:"heineken kanace",                                            qty:"1 koli ( 500 ml )",  price:"125 L/cp"},
  {id:617, cat:"BIRRA",    name:"hieneken kanace",                                            qty:"5+ arka ( 500 ml )", price:"120 L/cp"},
  {id:618, cat:"BIRRA",    name:"heineken kanace",                                            qty:"3+ arka ( 500 ml )", price:"122 L/cp"},
  {id:619, cat:"BIRRA",    name:"peja",                                                       qty:"5+ koli",            price:"78 L/cp"},
  {id:620, cat:"BIRRA",    name:"peja",                                                       qty:"1 koli",             price:"80 L/cp"},
  {id:621, cat:"BIRRA",    name:"ebar",                                                       qty:"5+ koli (500 ml )",  price:"77 L/cp"},
  {id:622, cat:"BIRRA",    name:"elbar",                                                      qty:"3+ koli ( 500 ml )", price:"80 L/cp"},
  {id:623, cat:"BIRRA",    name:"stella artois",                                              qty:"5+ koli",            price:"83 L/cp"},
  // ── BIRRA BELGE ────────────────────────────────────────────
  {id:624, cat:"BIRRAB",   name:"Leffe Bionde Shishe",                                        qty:"24cp x 330 ml",      price:"155 L/cp"},
  {id:625, cat:"BIRRAB",   name:"Stella Artois Shishe",                                       qty:"24cp x 330 ml",      price:"90 L/cp"},
  {id:626, cat:"BIRRAB",   name:"Liefmans Goudenband Shishe",                                 qty:"750 ml",             price:"750 L/cp"},
  {id:627, cat:"BIRRAB",   name:"Blanche de Namur Sishe",                                     qty:"750 ml",             price:"550 L/cp"},
  {id:628, cat:"BIRRAB",   name:"Mc Chouffe Shishe",                                          qty:"750 ml",             price:"680 L/cp"},
  {id:629, cat:"BIRRAB",   name:"St Bernardus Wit Shishe",                                    qty:"750 ml",             price:"700 L/cp"},
  {id:630, cat:"BIRRAB",   name:"St Bernardus Pater 6 Shishe",                                qty:"24cp x 330 ml",      price:"275 L/cp"},
  {id:631, cat:"BIRRAB",   name:"St Bernardus Prior 8 Shishe",                                qty:"12cp x 330 ml",      price:"300 L/cp"},
  {id:632, cat:"BIRRAB",   name:"St Bernardus Tripel Shishe",                                 qty:"12cp x 330 ml",      price:"300 L/cp"},
  {id:633, cat:"BIRRAB",   name:"St Bernardus Wit Shishe",                                    qty:"12cp x 330 ml",      price:"255 L/cp"},
  {id:634, cat:"BIRRAB",   name:"St Bernardus Abt 12 Shishe",                                 qty:"24cp x 330 ml",      price:"330 L/cp"},
  {id:635, cat:"BIRRAB",   name:"Blanche de Namur Shishe",                                    qty:"24cp x 330 ml",      price:"235 L/cp"},
  {id:636, cat:"BIRRAB",   name:"Trappistes Rochefort 8 Shishe",                              qty:"24cp x 330 ml",      price:"330 L/cp"},
  {id:637, cat:"BIRRAB",   name:"Orval Shishe",                                               qty:"24cp x 330 ml",      price:"300 L/cp"},
  {id:638, cat:"BIRRAB",   name:"La Chouffe Shishe",                                          qty:"24cp x 330 ml",      price:"325 L/cp"},
  {id:639, cat:"BIRRAB",   name:"Liefmans Goudenband Shishe",                                 qty:"24cp x 330 ml",      price:"330 L/cp"},
  {id:640, cat:"BIRRAB",   name:"Liefmans Kriek Brut",                                        qty:"750 ml",             price:"750 L/cp"},
  {id:641, cat:"BIRRAB",   name:"Duvel Shishe",                                               qty:"24cp x 330 ml",      price:"310 L/cp"},
  {id:642, cat:"BIRRAB",   name:"St Bernardus Ale Shishe",                                    qty:"750 ml",             price:"750 L/cp"},
  {id:643, cat:"BIRRAB",   name:"Trappistes Rochefort 6 Shishe",                              qty:"24cp x 330 ml",      price:"300 L/cp"},
  {id:644, cat:"BIRRAB",   name:"Trappistes Rochefort 10 Shishe",                             qty:"24cp x 330 ml",      price:"400 L/cp"},
  {id:645, cat:"BIRRAB",   name:"La Chouffe Blond Shishe",                                    qty:"750 ml",             price:"660 L/cp"},
  {id:646, cat:"BIRRAB",   name:"Mc Chouffe Shishe",                                          qty:"24cp x 330 ml",      price:"325 L/cp"},
  {id:647, cat:"BIRRAB",   name:"Duvel Shishe",                                               qty:"750 ml",             price:"720 L/cp"},
  {id:648, cat:"BIRRAB",   name:"Saison Dupont Shishe",                                       qty:"750 ml",             price:"700 L/cp"},
  {id:649, cat:"BIRRAB",   name:"Maredsous Blonde Shishe",                                    qty:"750 ml",             price:"650 L/cp"},
  {id:650, cat:"BIRRAB",   name:"Triple Karmeliet Shishe",                                    qty:"750 ml",             price:"820 L/cp"},
  {id:651, cat:"BIRRAB",   name:"Triple Karmeliet Shishe",                                    qty:"24cp x 330 ml",      price:"320 L/cp"},
  {id:652, cat:"BIRRAB",   name:"Deus Shishe",                                                qty:"750 ml",             price:"1000 L/cp"},
  {id:653, cat:"BIRRAB",   name:"St Bernardus Prior 8 Shishe",                                qty:"750 ml",             price:"750 L/cp"},
  {id:654, cat:"BIRRAB",   name:"St Bernardus Tripel Shishe",                                 qty:"750 ml",             price:"750 L/cp"},
  {id:655, cat:"BIRRAB",   name:"St Bernardus ABT 12 Shishe",                                 qty:"750 ml",             price:"850 L/cp"},
  {id:656, cat:"BIRRAB",   name:"Malonne Sur Lie Shishe",                                     qty:"750 ml",             price:"1900 L/cp"},
  {id:657, cat:"BIRRAB",   name:"Malonne Calvados Shishe",                                    qty:"750 ml",             price:"2200 L/cp"},
  {id:658, cat:"BIRRAB",   name:"Malonne Bourbon Shishe",                                     qty:"750 ml",             price:"2100 L/cp"},
  {id:659, cat:"BIRRAB",   name:"Malonne Cognac Shishe",                                      qty:"750 ml",             price:"2100 L/cp"},
  {id:660, cat:"BIRRAB",   name:"Gran Reserva Doppio Malto",                                  qty:"12cp x 500 ml",      price:"208 L/cp"},
  {id:661, cat:"BIRRAB",   name:"Queue De Charrue Shishe",                                    qty:"750 ml",             price:"600 L/cp"},
  // ── BIRRA VENDI ────────────────────────────────────────────
  {id:662, cat:"BIRRAV",   name:"Korca Shishe",                                               qty:"24cp x 330 ml",      price:"85 L/cp"},
  {id:663, cat:"BIRRAV",   name:"Vatan Kanace Zero",                                          qty:"24cp x 500 ml",      price:"70 L/cp"},
  {id:664, cat:"BIRRAV",   name:"Vatan Kanace Kuq e Zi 4%",                                   qty:"24cp x 500 ml",      price:"75 L/cp"},
  {id:665, cat:"BIRRAV",   name:"Stela Kanaçe",                                               qty:"24cp x 330 ml",      price:"50 L/cp"},
  {id:666, cat:"BIRRAV",   name:"Stela Shishe",                                               qty:"24cp x 330 ml",      price:"75 L/cp"},
  {id:667, cat:"BIRRAV",   name:"Stela Kanace",                                               qty:"24cp x 500 ml",      price:"75 L/cp"},
  // ── PAKETA & OFERTA ────────────────────────────────────────
  {id:668, cat:"PAKETA",   name:"Uje Lajthiza",                                               qty:"20kl+1kl Falas 12cp x 0.5 L", price:""},
  {id:669, cat:"PAKETA",   name:"Peroni Shishe + Jumbo Tortilla",                             qty:"2kl 24cp x 330 ml + 1 Jumbo Tortilla 350 gr", price:""},
  {id:670, cat:"PAKETA",   name:"Amita",                                                      qty:"10 kl 24cp x 330 ml", price:""},
  {id:671, cat:"PAKETA",   name:"Barista Sole",                                               qty:"5 koli",             price:""},
  {id:672, cat:"PAKETA",   name:"Milbar",                                                     qty:"5 koli",             price:""},
  {id:673, cat:"PAKETA",   name:"Heineken Kanace",                                            qty:"5 Arka 330 ml",      price:""},
  {id:674, cat:"PAKETA",   name:"Heineken Kanace",                                            qty:"3 Arka 330 ml",      price:""},
  {id:675, cat:"PAKETA",   name:"Elbar Kanace",                                               qty:"5 Arka 500 ml",      price:""},
  {id:676, cat:"PAKETA",   name:"Elbar Kanace",                                               qty:"3 Arka 500 ml",      price:""},
  {id:677, cat:"PAKETA",   name:"Heineken Kanace",                                            qty:"5 Arka 500 ml",      price:""},
  {id:678, cat:"PAKETA",   name:"Heineken Kanace",                                            qty:"3 Arka 500 ml",      price:""},
  {id:679, cat:"PAKETA",   name:"Peroni Nastro Shishe",                                       qty:"5 Arka 330 ml",      price:""},
  {id:680, cat:"PAKETA",   name:"Peroni Nastro",                                              qty:"3 Arka 330 ml",      price:""},
  {id:681, cat:"PAKETA",   name:"Peroni Kanace",                                              qty:"5 Arka 500 ml",      price:""},
  {id:682, cat:"PAKETA",   name:"Peroni Kanace",                                              qty:"3 Arka 500 ml",      price:""},
  {id:683, cat:"PAKETA",   name:"Stella Artois Shishe",                                       qty:"3 Arka 330 ml",      price:""},
  {id:684, cat:"PAKETA",   name:"Amita",                                                      qty:"5 kl 24cp x 330 ml", price:""},
  {id:685, cat:"PAKETA",   name:"Stella Artois Shishe",                                       qty:"5 Arka 330 ml",      price:""},
  {id:686, cat:"PAKETA",   name:"Ndujia Piccante",                                            qty:"5+1 FALAS",          price:""},
  {id:687, cat:"PAKETA",   name:"Kotolete",                                                   qty:"e vogel 6 kg + e madhe 5 kg", price:""},
  {id:688, cat:"PAKETA",   name:"Rosto Vici",                                                 qty:"5 kg",               price:""},
  {id:689, cat:"PAKETA",   name:"Fish Sticks",                                                qty:"5 copë + 1 FALAS",   price:""},
  {id:690, cat:"PAKETA",   name:"Tramezzini Mix",                                             qty:"6cp + 1 FALAS",      price:""},
  {id:691, cat:"PAKETA",   name:"Burger Buns",                                                qty:"60 copë x 110 g",    price:""},
  {id:692, cat:"PAKETA",   name:"Holla Barista + Kraco",                                      qty:"5 koli 3.8% 12cp x 1 L + 5 Kraco 5B FALAS", price:""},
  {id:693, cat:"PAKETA",   name:"Glina & Glina Limon",                                        qty:"10kl+1kl Falas 12cp x 0.5 L", price:""},
  {id:694, cat:"PAKETA",   name:"Coca Cola Fanta Sprite",                                     qty:"5kl 0.33 L",         price:""},
  {id:695, cat:"PAKETA",   name:"Barista Sart + Kraco",                                       qty:"5 koli 3.8% 12cp x 1 L + 5 Kraco 5B FALAS", price:""},
  {id:696, cat:"PAKETA",   name:"Peroni Kanace",                                              qty:"3KL 24 x 330 ml",    price:""},
  {id:697, cat:"PAKETA",   name:"Gotë Kartoni për Kafe",                                      qty:"10 pako 3 oz + 1 pako FALAS", price:""},
];
